import turtle
a=turtle.Pen()
a. shape('triangle')
a. color('red')
a.circle(100)
a. right(72)
a.color('yellow')
a. shape('triangle')
a.circle(100)
a. right(72)
a.color('navy')
a. shape('triangle')
a.circle(100)
a. right(72)
a.color('light green')
a. shape('triangle')
a.circle(100)
a. right(72)
a.color('purple')
a. shape('triangle')
a.circle(100)

turtle.exitonclick()